### ISSUE TITLE
Add Atollic True studio projects

### ISSUE THREAD

**Issue by VaDimTag** [STM32cube/STM32cubeF7#1]
Can you please add Atollic True studio projects to the cubeF7 projects and examples folders (now there are only EWARM, MDK-ARM, SW4STM32 projects). This is reasonable because ST has acquired Atollic.

**Comment by aurimasniekis** [comment]
This is only mirror of official zip file

**Comment by VaDimTag** [comment]
Nevertheless, will you add what I am asking for?

**Comment by aurimasniekis** [comment]
This is a mirror, which means I don't control its content. Everything that is available inside the zip file ST provides is copied to this repository.

**Comment by VaDimTag** [comment]
OK, sorry, I have thought that this is official mirror.
